version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
