// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"whois-go/internal/handler"
	"whois-go/internal/repository"
	"whois-go/internal/server"
	"whois-go/internal/service"
	"whois-go/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	systemService := service.NewSystemService(serviceService, logger)
	systemHandler := handler.NewSystemHandler(handlerHandler, systemService)
	engine := server.NewServerHTTP(logger, systemHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewSystemService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewSystemHandler)
